### ISSUE TITLE
Unit Selection

### ISSUE THREAD

**Issue by Scott-Tatham** [Scott-Tatham/2016-S1T2-C42B-BattlingRoyals#2]
Allowing a primitive version of left click selection of units.
- [x] Allowing selection of test unit.
- [x] Allowing selection of all units.
- [x] Allowing selection of multiple units.

**Comment by Scott-Tatham** [comment]
Selection of multiple units is underway there are a few minor tweaks to be made to other selection components but for the best part it is complete.
