### ISSUE TITLE
Unit Movement

### ISSUE THREAD

**Issue by Scott-Tatham** [Scott-Tatham/2016-S1T2-C42B-BattlingRoyals#8]
- [x]  Units move to given positions.
- [x] Can take a player determined route, such as arcs, loops and zig zagging.
- [x]  Player units follow enemy when targeted.

**Comment by Scott-Tatham** [comment]
Have some small issues with player following enemy. Should be fixed soon.
