### ISSUE TITLE
In-game UI

### ISSUE THREAD

**Issue by DementedYoukai** [Scott-Tatham/2016-S1T2-C42B-BattlingRoyals#9]
- [x]  Timer
- [ ]  Score system (might)
- [ ]  Win/Lose UI
- [ ]  Unit information (placing cursor on unit to display information)
- [ ] Pause Menu
